### ISSUE TITLE
Item serialization to {$ref} broken in v1.4.0

### ISSUE THREAD

**Issue by lyschoening** [biosustain/potion-node#32]
In get requests, items serialize to the JSON representation of the item including internal state. They should serialize to {$ref} objects. 

I assume this is due to: https://github.com/biosustain/potion-node/commit/628b0aa92b2cb65ad4bd20889e5028acf3dadc22

I would suggest reverting that change.

**Comment by rolandjitsu** [comment]
Strange, I thought we had tests for that. I'll add some tests and see what's going on. I'll push a fix as soon as I can.

**Comment by rolandjitsu** [comment]
@lyschoening I tracked down the issue and I think it's fixed. Could you try it out and let me know? I published `v1.5.0` with all the changes, though circular references will not work (work in progress on that one).

**Comment by lyschoening** [comment]
@rolandjitsu It seems as if the API prefix now gets prepended twice. (e.g. `{"$ref": "/api/api/foo/123"}`). Not sure if that is a separate issue or the same issue.

May I ask what the original motivation for the change is? It's quite a lot of work, obviously, to get it working and, at least from my perspective, not much gain (more code, no additional functionality).

**Comment by rolandjitsu** [comment]
@lyschoening that looks like a separate issue. I just wanted to reuse the same object mapper instead of having two.

I'll reopen this and add another test for this scenario, but I pushed some changes with a lot more tests and I'm actually testing the `toPotionJSON()` method.

**Comment by lyschoening** [comment]
As far as I can see, `deepOmap()` was only used once. Could have gotten rid of the function and done something like:

```
const deepEntryMapper = (key, value) => typeof value === 'object' ? deepEntryMapper(key, value) : [toCamelCase(key), value]
omap(obj, deepEntryMapper)
```

Also not sure how the prefix is related. The prefix issue wasn't there in 1.3.0 though.

**Comment by rolandjitsu** [comment]
True, it was only used to parse schema JSON which only needed the keys to be converted to camelcase. I'll just do what you suggest, I'm not even sure why I made the `deepOmap()` in the first place 😕

**Comment by rolandjitsu** [comment]
Though actually schema has arrays as well, and those cannot be parsed as objects because the keys would be the indexes, so that might have been why I made the method, but it's hard to remember precisely why.

**Comment by rolandjitsu** [comment]
@lyschoening I just published `v1.5.1`, the issue with the prefix being appended twice should be fixed now.

**Comment by lyschoening** [comment]
@rolandjitsu seems to work!

**Comment by lyschoening** [comment]
We're still having issues. Could it be that POST requests are handled differently with respect to this bug?

The original issue, that items don't get converted to {$ref} objects also applies to POST requests.

**Comment by rolandjitsu** [comment]
Hmmm, all methods should go through the same serialization, look at [potion.ts#L120](https://github.com/biosustain/potion-node/blob/master/src/core/potion.ts#L120), it will call `.serialize()` which in turn calls [toPotionJSON](https://github.com/biosustain/potion-node/blob/master/src/core/utils.ts#L111).

I will try to add a test case for POST and see if I get the same behaviour.

**Comment by lyschoening** [comment]
Sorry, it looks like `v1.5.2` fixed this issue
